### ISSUE TITLE
Popover Component?

### ISSUE THREAD

**Issue by WillGeller** [drozhzhin-n-e/ng2-tooltip-directive#57]
Great `tooltip` component! I am using it now in an Angular Hybrid application that also uses ui-bootstrap on the angularJs side. I'm unable to use `ng-bootstrap` due to conflicting CSS versions of the Bootstrap library. Your directive has been a great drop-in replacement.

I also am upgrading a component that needs a popover type functionality. I see I can use this tooltip with click to trigger, render HTML content in the tooltip, but then can not interact with links within the tooltip.

Any idea when the popover component will be ready. I see on your website it says it is in progress. Any idea of any alternatives or workarounds?

**Comment by drozhzhin-n-e** [comment]
@WillGeller I am glad that the tooltip was useful to you. I have already completed the popover component, but have not published it because I do not have time to support it. I do not plan to use it in my projects, so I do not get any benefit from its development. Would you be willing to pay for a license to use it?

**Comment by drozhzhin-n-e** [comment]
I forgot to write to you that this component is made http://ivylab.space/popover
